# Example Site settings

#google_analytics: UA-NNNNNNNN-N

home_page:
  - index.md

header_pages:
  - about.md

collections:
  dnd:
    output: true

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
